### PR TITLE
Dealias types when collecting parents

### LINKED ISSUE #500: API summary lists `ServiceWorkerContainer` as a Scala trait

### PR DESCRIPTION
**Pull request by japgolly**
Fixes #500

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]
Ahh, because it was extending the type alias. Makes sense 👍

**Comment by japgolly** [comment]
@armanbilge Yeah also pulls in other inherited members which was a big whoopsey.

I'll merge cos I see your approval (dude, let just merge after we assign one and other for review) and in response to your question in the other PR: yeah cool, let's get a 1.2.0 out! You wanna do it?

**Comment by armanbilge** [comment]
> I'll merge cos I see your approval (dude, let just merge after we assign one and other for review)

Fine by me! Unless its straightforward I usually hesitate cause at least I sometimes have one more post-review afterthought to slip in 😆 

> yeah cool, let's get a 1.2.0 out! You wanna do it?

Yep, it's just making a tag right! Do we want to try and fix the auto-release drafter thingy first? I think it's the quickest way to make sure we acknowledge all the contributions.

**Comment by japgolly** [comment]
> Yep, it's just making a tag right! Do we want to try and fix the auto-release drafter thingy first? I think it's the quickest way to make sure we acknowledge all the contributions.

I couldn't be arsed doing it myself (because it's something new that wasn't present for all of the previous releases, so don't mind skipping until 2.0), but OTOH if you're free and willing to do that it would also be appreciated so, up to you :) I've got sick kids this week so I'll probably have to relieve my wife soon anyway. Can I just ask, once you've done the release, would you mind doing announcement comms? I usually just do Twitter and Reddit. Should be do more like https://users.scala-lang.org/ ? I'll leave it to you and your judgement :)

**Comment by armanbilge** [comment]
Thanks, leave it to me! The scala-users post you made got a lot of views so seems a good venue there and I can also post on the Scala.js Discord/gitter, I think you have more twitter followers though :)

Hope your kids feel better soon!! Don't get sick yourself :)

**Pull request merged**
