### PR TITLE
Support Scala 3

### PR DESCRIPTION
**Pull request by armanbilge**
Rebases @russwyte's work in #446 per @sjrd's review comment.

### CODE REVIEW

**Comment by armanbilge** [comment]
@sjrd formatting fixed

**Review by sjrd — APPROVED** [review]

**Comment by armanbilge** [comment]
Thanks for approving! I hope you can cut a release after merging :)

**Comment by sjrd** [comment]
> Thanks for approving! I hope you can cut a release after merging :)

See https://github.com/scala-js/scala-js-dom/issues/451

**Comment by russwyte** [comment]
Thanks for keeping this moving! Cheers! 👍

**Pull request merged**
