### PR TITLE
Upgrade to scalajs-0.6.7

### PR DESCRIPTION
**Pull request by danielwegener**
Remove dom.raw.Promise. Remove invalid js.native annotations.

### CODE REVIEW

**Comment by sjrd** [comment]
> Upgrade to scalajs-0.6.7. Remove dom.raw.Promise. Remove invalid js.native annotations.

Those 3 sentences sound very much like 3 commits to me ;)

**Comment by danielwegener** [comment]
Yeah but each committed individually would produce two broken commits :)

**Comment by sjrd** [comment]
1. Remove invalid annotations
2. Upgrade
3. Use `js.Promise`

Doesn't that work?

**Comment by danielwegener** [comment]
Aww but not as it really happened! ;) Sure! If it makes thinks clearer.

**Comment by sjrd** [comment]
There are some `Promise`-related changes in your first commit, which should be in the third commit.
That's all.

**Comment by mseddon** [comment]
Should we perhaps have a type alias where the old Promise was with a `@deprecated` message pointing to the new location?

**Comment by sjrd** [comment]
Yes, good point.

**Comment by danielwegener** [comment]
@mseddon @sjrd :ship: :it: !

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
