### PR TITLE
Clean up config traits

### PR DESCRIPTION
**Pull request by sjrd**
And deprecate all the `def apply`-based constructors, in favor of the `new Foo { ... }` syntax.

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]
This is really great (thanks for continuing to contribute!!) and very huge ... honestly I skimmed most of the changes. A lot of this code I'll be revisiting anyway as we de-namespace.

@japgolly seems to be on a bit of a hiatus atm but hopefully he'll be back soon :)

**Review by japgolly — APPROVED** [review]

**Comment by japgolly** [comment]
Fantastic changes, thanks @sjrd . LGTM

**Comment by armanbilge** [comment]
@sjrd do you have any more planned/suggested cleanups for 2.0? I'm trying to get an idea of remaining blockers. Thanks!

**Comment by sjrd** [comment]
I'd like to have separate definitions of `sealed traits` for Scala 3 that would be `opaque type`s instead.

I think that's the only thing I have left.

**Pull request merged**
