### PR TITLE
Add key codes for F1 to F12

### PR DESCRIPTION
**Pull request by japgolly**

### CODE REVIEW

**Comment by sjrd** [comment]
Hum, uppercase `F1`? Isn't that more common?

**Comment by japgolly** [comment]
There are two conventions that motivated me to use lowercase.

1. All the other vals in that `object` are lowercase.
2. Scala variables are often lowercase with uppercase representing types.

Happy to change it if you'd still prefer I do.

**Comment by sjrd** [comment]
Ah, you're right about 1. I believe that's a mistake we should fix globally. (with deprecated aliases)
Scala variables are lowercase, but *constants* are typically written with an uppercase.

**Comment by japgolly** [comment]
np, replaced with #105

**Pull request closed without merging**
