### PR TITLE
Add NonDocumentTypeChildNode

### PR DESCRIPTION
**Pull request by japgolly**

### CODE REVIEW

**Comment by japgolly** [comment]
**Don't merge yet**, this doesn't work properly.

Using this, I get:
```
Uncaught TypeError: Cannot read property 'previousElementSibling' of null
```

So... `null` and `undefined` aren't the same in Scala.JS?

**Comment by sjrd** [comment]
No, [`null` is `null` and `undefined` is `()`](http://www.scala-js.org/doc/js-interoperability.html) (unit). Imagine how much of everything would make no sense whatsoever if two values that are different in js were "the same" in Scala.js ... I can't even fathom the situation.

**Comment by lihaoyi** [comment]
>  Imagine how much of everything would make no sense whatsoever

lol that's just every day in Javascript land...

**Comment by japgolly** [comment]
Hehe. Well let's put it down to misremembering and wishingful thinking :)

Corrected. Should be good to go now.

**Comment by sjrd** [comment]
LGTM

> lol that's just every day in Javascript land...

No no. Your snippet still makes sense. Here we're talking about an entirely different kind of nonsense. The kind which truly has *no* sense. As opposed to *some* sense, even if unintuitive and possibly difficult to reason about.

**Pull request merged**
