### PR TITLE
Fix #445 return type for Header#get

### LINKED ISSUE #445: Headers#get won't return undefined but typed as js.UndefOr
The headers#get method returns a header value or null. So this method won't return undefined. but it's typed with js.UndefOr.
https://developer.mozilla.org/en-US/docs/Web/API/Headers/get
https://github.com/scala-js/scala-js-dom/blob/5a502ad998eb3f9a6a38a4494a30cc9a55f0c916/src/main/scala/org/scalajs/dom/experimental/Fetch.scala#L312

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by japgolly** [comment]
1. Are you absolutely sure it will never return `undefined` in any circumstance/browser?
2. Breaks compat. Will have to target 2.x

**Comment by armanbilge** [comment]
Good questions 🤔 

1. Not according to the spec. I have no idea how to answer that question in general 🙃 
2. I'm still confused about what exactly breaks compat. I assume this is breaking source compat but not binary compat?

**Comment by japgolly** [comment]
1. Gotta just google it I'm afraid. I usually start with mdn, then if needed read through the linked specs. 
2. Hmmm interesting, actually my understanding of binary compat when it comes to SJS facades is full of unverified assumptions so I'm not much of an authority there. But source compat definitely breaks. Imagine `.get(???).isDefined`

**Comment by armanbilge** [comment]
1. Yup, I checked in MDN and it didn't say anything about `undefined`, just possibly returns `null`.
2. I got an excellent primer on binary compat for facades here: https://github.com/scala-js/scala-js-dom/pull/461#issuecomment-894829615

Regarding source compat: we should have clarified what freezing backwards compat looks like for the next 1.x. I assumed we'd freeze bincompat (semantic versioning) but not source compat. If we also freeze source compat, then many PRs are no longer applicable to 1.x. I'm fine either way, let's just be really clear on this :)

**Comment by sjrd** [comment]
I can confirm that this PR does not break binary compatibility. (In a Scala class, it would, but not in a JS facade.)

**Review by japgolly — APPROVED** [review]

**Comment by japgolly** [comment]
Thanks @armanbilge :+1:

**Pull request merged**
