### PR TITLE
Add the Notification API

### PR DESCRIPTION
**Pull request by coreyauger**

### CODE REVIEW

**Comment by mseddon** [comment]
Oh, you don't need to create a new PR to change this- you can simply "git push origin <branch> -f" and github is smart enough to update the code but keep the notes.  I did this first time I committed here https://github.com/scala-js/scala-js-dom/pull/14 :)

To quote Sébastien when I did it: "this is better than reopening a new PR because comments are kept and correlated with the new commits for lines that have not changed."

**Comment by coreyauger** [comment]
doh! .. sorry I did a re-checkout.  I also forgot to update the import in the example which i have done now.    How do I reissue the pull request with the fix?

**Comment by mseddon** [comment]
:+1: got it before I finished typing.  The only other issue is you're PR'ing from master (should have caught this earlier, blah) onto master which causes issues if we need to go through history.  The PR should be a single commit for this, in a branch, say `notification-api`

**Comment by mseddon** [comment]
The way to do this is first wind back your working directory two commits, but keep your changes.  `git reset --soft HEAD~2` should put you there.  Once that is done you can git checkout -b notification-api, and commit these fixes as usual, then `git push origin notification-api`.  One moment while I find out if there is a way to modify the branch of an in-flight PR.

**Comment by mseddon** [comment]
bleh. https://github.com/isaacs/github/issues/18 seems it's not possible. once you have a `notification-api` branch on your fork, you will have to send another PR from your fork's `notification-api` branch onto our `master` and close this one. :)

**Comment by coreyauger** [comment]
Ok thanks for your help :+1:

**Comment by mseddon** [comment]
np. my first few PR's were a total car accident ;)

**Comment by coreyauger** [comment]
I have used this line twice already.. lol :)

**Comment by mseddon** [comment]
;)        *ReverseChainingContextSingleSubstitution

**Pull request closed without merging**
