### PR TITLE
Fix signatures for oncut, oncopy and onpaste

### PR DESCRIPTION
**Pull request by swhgoon**
Fix signatures for oncut, oncopy and onpaste.

### CODE REVIEW

**Comment by mseddon** [comment]
(facepalm) I have no idea how they got that type.. LGTM.

**Comment by mseddon** [comment]
@swhgoon was that intentional?

**Comment by swhgoon** [comment]
@mseddon I used `dom.document.addEventListener("copy", fn)` instead...

**Comment by mseddon** [comment]
Ah, the only thing is, if you could reword your commit message to something more meaningful like "Fix signatures for oncut, oncopy and onpaste." and @sjrd will merge.  Thanks!

**Comment by sjrd** [comment]
@swhgoon : @mseddon meant the title of the *commit*. It's good to change the title of the PR, too, but most importantly it's the commit title that matters. You can edit it easily with `git commit --amend` while the branch of this PR is checked out.

**Comment by sjrd** [comment]
This ended up being done in 9bb10dca6534db14956c49a5b168c0b47ffb794a.

**Pull request closed without merging**
