### PR TITLE
Sort API members by name

### PR DESCRIPTION
**Pull request by armanbilge**
@japgolly is this what you are looking for?

### CODE REVIEW

**Comment by japgolly** [comment]
Close! Types still need to come first though. Sorting key should be `(prefix, name, body)`

**Comment by japgolly** [comment]
Wait, no no no. Yeah I didn't think it would be this easy. `name` here is the scope name, not the member name. The member name is currently lost from `MutableState`'s pov. You'd have to change the `.add` methods in `MutableState.Scope` to also accept name and then plumb it through

**Comment by armanbilge** [comment]
Hmm ok maybe this is more one for you 😅

**Comment by japgolly** [comment]
hehe np

**Comment by japgolly** [comment]
Superseded by #484

**Pull request closed without merging**
