### PR TITLE
Node: Fix calls to insertBefore() with one argument

### PR DESCRIPTION
**Pull request by tindzk**

### CODE REVIEW

**Comment by sjrd** [comment]
Actually, [MDN says](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore) that *both* arguments are required. The default value should therefore be removed altogether.

**Comment by sjrd** [comment]
Note that the value put after `=` doesn't matter to the compiler in a JS facade. It only serves documentation purposes. So putting `null` there will *not* make the compiler add a `null` if you don't specify the second argument.

**Comment by tindzk** [comment]
Ok, thanks for clearing this up. I updated the commit accordingly.

**Comment by sjrd** [comment]
LGTM, thanks.

**Pull request merged**
