### PR TITLE
File size as Double

### PR DESCRIPTION
**Pull request by Starzu**
It's possible to select a file bigger than 2GB.

### CODE REVIEW

**Comment by sjrd** [comment]
This is most certainly incorrect, as Longs are not JavaScript numbers. If JS numbers larger than `Int.MaxValue` are to be accepted, then the type must be `Double`.

**Comment by Starzu** [comment]
@sjrd Right, my bad. ;)

**Comment by ritschwumm** [comment]
i think i'd still like an Int53 type i could use in these situations...

**Comment by mseddon** [comment]
@ritschwumm see https://github.com/scala-js/scala-js/issues/2170 for a possible implementation.

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
