### PR TITLE
Added a method to AjaxException to check for timeout status.

### PR DESCRIPTION
**Pull request by ochrons**
Replaces #95

### CODE REVIEW

**Comment by sjrd** [comment]
OK, but what's the "Change-Id" in the commit message?

**Comment by ochrons** [comment]
Ah, that's something we use for Gerrit and it gets automatically added to commits.

**Comment by sjrd** [comment]
Er, could you remove it?

**Comment by ochrons** [comment]
Doh, it of course keeps creating it again... gotta remove the script :)

**Comment by sjrd** [comment]
LGTM Thanks.

**Pull request merged**
