### PR TITLE
fix refrence in JSName to point to correct javascript object

### PR DESCRIPTION
**Pull request by coreyauger**
Was getting an error when calling new Notification.  Changing it to the below JSName appears to fix the problem.

### CODE REVIEW

**Comment by mseddon** [comment]
LGTM, @sjrd okay to merge?

**Comment by mseddon** [comment]
Only issue is the commit message has typos :)
Perhaps "Fix @JSName reference for Notification".

**Comment by coreyauger** [comment]
Did I mess this up ?  ... fixed the commit message but now there are conflicts.  Do I need to resolve these on my end.  Sorry for all the dumb questions.

**Comment by sjrd** [comment]
Hum, yep, I think you messed it up ^^ Apparently you introduced into the commit changes coming from other PRs and other stuff. No idea how you got there ^^

At this point, since the change was a one-liner IIRC, the easiest is probably to `git reset --hard master` (THIS WILL DELETE ALL YOUR WORK) then re-do the change.

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
