### PR TITLE
Add experimental PointerLock and Fullscreen API

### PR DESCRIPTION
**Pull request by danielwegener**
That's the last one for the moment :) (promised!).

### CODE REVIEW

**Comment by danielwegener** [comment]
The fullscreen whatwg spec seem to be a little ahead of the browsers. `Document.exitFullscreen` and `Element.requestFullscreen` seem not to return a promise but `Unit` (I tried to express that with the return type `Promise[Unit] | Unit`). 

`onfullscreenchanged`and `onfullscreenerror` do not seem to be implemented at all so I left them out.

**Comment by sjrd** [comment]
> `Promise[Unit] | Unit`

Hum ... That's a very weird and unpractical result type :-s

I guess the least bad option would be `js.UndefOr[Promise[Unit]]`.

**Comment by sjrd** [comment]
Would be nice to document why in the Scaladoc, btw.

**Comment by danielwegener** [comment]
@sjrd Good point. Fixed. Added `onfullscreenchanged` and `onfullscreenerror` but added a note that they may not be available.

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
