### PR TITLE
Add experimental Vibration API

### PR DESCRIPTION
**Pull request by mseddon**
Get the ball rolling with  `org.scalajs.dom.experimental`. by adding the vibration api

### CODE REVIEW

**Comment by mseddon** [comment]
... actually remembered to commit working version and unbork commit message. *sigh*.

**Comment by mseddon** [comment]
`[error] SERVER ERROR: Connection timed out url=https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom`

Jenkins network connectivity issue? This test needs to be re-run. :(

**Comment by mseddon** [comment]
Implicit conversion now has zero overhead, thanks to advice from @gzm0.  I've confirmed this by looking at compiler output in `fastOptJS`.  Okay to merge pending review, but no mad rush :)

**Comment by lihaoyi** [comment]
Thanks! =D

**Pull request merged**
