### PR TITLE
* added the html5 Notification api 

### PR DESCRIPTION
**Pull request by coreyauger**
Added Notification API as outlined here (https://developer.mozilla.org/en-US/docs/Web/API/notification)

### CODE REVIEW

**Comment by coreyauger** [comment]
I was thinking that it would be nice to beak out the notification options into an options trait .. rather then passing it in as a js.Object like I am doing now.  Thoughts?

**Comment by mseddon** [comment]
Yep, I'd definitely do that if you can, with a companion object to construct it, see https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/raw/lib.scala#L3824

It looks like this is not supported under IE or mobile browsers, so it may also better live in the experimental package.  We use implicit conversions defined in there to overlay support for apis that won't "just work" everywhere, to avoid confusion, see: https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/experimental/Vibration.scala for an example.

**Comment by mseddon** [comment]
I would also change the name of the commit to fall in line with convention.  It should read `Add the Notification API" - present tense, no leading *. (and "html5" is possibly redundant here).

**Comment by coreyauger** [comment]
Sounds good... I am going to close this and issue a new pull request.  Thanks.

**Pull request closed without merging**
