### PR TITLE
Merge series/1.x into master

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by armanbilge** [comment]
@japgolly I'm sure I overlooked something but I think this is 90% of the way there. BTW no API reports are generated for Scala 3, probably due to lack of scalafix support, but it's probably fine since it's binary compatible with 2.13 anyway.

**Comment by japgolly** [comment]
LGTM

**Comment by armanbilge** [comment]
🎉 should we make master the default branch again?

**Comment by japgolly** [comment]
> should we make master the default branch again?

No preference here :) Up to you

**Comment by armanbilge** [comment]
Sorry, I already switched back to master when you weren't looking 😉 it's important, because it's where GH will automatically base contributor's PRs against. I switched to `series/1.x` because a poor soul got confused why they couldn't `prePR` their PR to master 😅

**Comment by japgolly** [comment]
Nice! Full steam ahead!! :rocket:

**Pull request merged**
