### PR TITLE
Keycode changes

### PR DESCRIPTION
**Pull request by japgolly**
* Added key codes F1~F12
* Made KeyCodes camel-case
* Changed `val` to `final val`

Addresses #103 and #104.
Supersedes #105.

### CODE REVIEW

**Comment by sjrd** [comment]
OK. Could you just rename the commit messages to use the present tense, i.e., Made -> Make and Added -> Add.
That's all.

**Comment by japgolly** [comment]
You make me feel like a hamster on a wheel @sjrd. How about now? :pray:

**Comment by sjrd** [comment]
LGTM :)

**Comment by japgolly** [comment]
we did it! Thank you :sun_with_face:

**Pull request merged**
