### PR TITLE
Fix #282: Upgrade to Scala.js 0.6.16, Scala 2.11.11, 2.12.2 and add Scala 2.13.0-M1.

### LINKED ISSUE #282: cross-publish for 2.13.0-M1

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by sjrd** [comment]
`.travis.yml` also needs to be updated.

The commit message should be

    Fix #282: Upgrade to Scala.js 0.6.16 and add Scala 2.13.0-M1.

(see for example db62b2ee378ff8a1b49d2fbedf66123ab8999dba for a precedent)

**Comment by MasseGuillaume** [comment]
Done ;-).

I also bumped 2.12 and 2.11.

**Comment by MasseGuillaume** [comment]
Thanks!
Is it possible to publish 0.9.2?

**Comment by sjrd** [comment]
Done.

**Comment by MasseGuillaume** [comment]
Merci!

**Pull request merged**
